version: 0.2

phases:
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the source code"
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
    files:
        - target/order-service.jar
    discard-paths: yes
